# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 23:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostPetsDetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='type_pet',
            field=models.CharField(default='000', max_length=100),
        ),
        migrations.AlterField(
            model_name='lostpet',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
