# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostPetsDetails', '0002_auto_20170827_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='age',
            field=models.IntegerField(default='0'),
        ),
    ]
