# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostPetsDetails', '0003_lostpet_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='type_pet',
            field=models.CharField(default='pet', max_length=100),
        ),
    ]
