# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-27 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lostPetsDetails', '0004_auto_20170827_1021'),
    ]

    operations = [
        migrations.AddField(
            model_name='lostpet',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
