# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-19 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lostPetsDetails', '0006_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='ticker',
            new_name='studentName',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='close',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='open',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volume',
        ),
        migrations.AddField(
            model_name='stock',
            name='studentId',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='stock',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
